# Generated by Django 3.2.6 on 2022-01-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20220128_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='age',
        ),
        migrations.RemoveField(
            model_name='record',
            name='lastAction',
        ),
        migrations.RemoveField(
            model_name='record',
            name='level',
        ),
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='status',
        ),
        migrations.RemoveField(
            model_name='record',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='record',
            name='userId',
        ),
        migrations.AddField(
            model_name='record',
            name='Def',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='Dex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='Spd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='Str',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='TotalStats',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='UserId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
