# Generated by Django 3.2.6 on 2022-01-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20220128_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='TotalStats',
            field=models.IntegerField(null=True),
        ),
    ]
